#!/bin/bash
# Simple deployment with direct file modification

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${GREEN}Simple deployment script${NC}"

# Check .env
if [ ! -f .env ]; then
    echo -e "${RED}Error: .env file not found!${NC}"
    exit 1
fi

# Load variables
export $(cat .env | grep -v '^#' | xargs)

echo "Using domain: $DOMAIN_NAME"
echo "Apps Script URL: ${GOOGLE_APPS_SCRIPT_URL:0:50}..."

# Stop all containers
echo -e "${GREEN}Stopping all containers...${NC}"
docker stop $(docker ps -q --filter "name=kaiumtu") 2>/dev/null || true
docker rm $(docker ps -aq --filter "name=kaiumtu") 2>/dev/null || true

# Create a temporary copy of config.js with actual values
echo -e "${GREEN}Creating config with actual values...${NC}"
cat > ../js/config.local.js << EOF
// Configuration for MTÜ Kaiu Kodukant Website
// Auto-generated by deploy-simple.sh

// Google Apps Script Backend URL
window.GOOGLE_APPS_SCRIPT_URL = '$GOOGLE_APPS_SCRIPT_URL';

// reCAPTCHA Site Key
window.RECAPTCHA_SITE_KEY = '$RECAPTCHA_SITE_KEY';
EOF

# Backup original and use local
cp ../js/config.js ../js/config.js.backup 2>/dev/null || true
cp ../js/config.local.js ../js/config.js

echo -e "${GREEN}Starting Caddy container...${NC}"
docker-compose -f docker-compose.simple.yml up -d

# Wait and check
sleep 5
echo -e "${GREEN}Container status:${NC}"
docker ps | grep kaiumtu

echo -e "${GREEN}Deployment complete!${NC}"
echo "Site available at: https://$DOMAIN_NAME"
echo ""
echo "Check logs: docker logs -f kaiumtu-simple"