# Production Docker Compose with build-time variable substitution
services:
  caddy:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
      args:
        - GOOGLE_APPS_SCRIPT_URL=${GOOGLE_APPS_SCRIPT_URL}
        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    container_name: kaiumtu-production
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local