# Docker Compose for MTÜ Kaiu Kodukant Website
# Simplified production deployment with build-time variable injection

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - GOOGLE_APPS_SCRIPT_URL=${GOOGLE_APPS_SCRIPT_URL}
        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
    container_name: kaiumtu
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    volumes:
      # Use production Caddyfile by default
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      # Persist Caddy data (certificates, etc.)
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - web

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  web:
    driver: bridge