# Simplified production deployment
services:
  web:
    image: caddy:2.7-alpine
    container_name: kaiumtu-simple
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      # Mount source files directly (config.js must be pre-edited)
      - ../:/usr/share/caddy:ro
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local