# Docker Compose for MTÜ Kaiu Kodukant Website
# Simplified production deployment with build-time variable injection

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        GOOGLE_APPS_SCRIPT_URL: ${GOOGLE_APPS_SCRIPT_URL}
        RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
    container_name: kaiumtu
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    volumes:
      # Use production Caddyfile by default
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      # Persist Caddy data (certificates, etc.)
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - web
    depends_on:
      - api

  api:
    build:
      context: ../
      dockerfile: docker/api/Dockerfile
    container_name: kaiumtu-api
    restart: unless-stopped
    environment:
      - TZ=Europe/Tallinn
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_PATH=/data/forms.db
      - ALLOWED_DOMAIN=https://${DOMAIN_NAME:-localhost}
      - API_DOMAIN=https://api.${DOMAIN_NAME:-localhost}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-noreply@kaiukodukant.ee}
      - INFO_EMAIL=${INFO_EMAIL}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT:-https://s3.pilw.io}
      - S3_BUCKET=${S3_BUCKET:-kaiugalerii}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION:-eu-west-1}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_SHEETS_ENABLED=${GOOGLE_SHEETS_ENABLED:-false}
      - MEMBERSHIP_SPREADSHEET_ID=${MEMBERSHIP_SPREADSHEET_ID}
      - CONTACT_SPREADSHEET_ID=${CONTACT_SPREADSHEET_ID}
      - GOOGLE_SERVICE_ACCOUNT=${GOOGLE_SERVICE_ACCOUNT}
      - DATA_RETENTION_DAYS=${DATA_RETENTION_DAYS:-0}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-200}
      - WEATHER_UPDATE_INTERVAL=${WEATHER_UPDATE_INTERVAL:-14400}
      - WEATHER_LOCATION_COORDS=${WEATHER_LOCATION_COORDS:-59.0106;25.0597}
      - WEATHER_LOCATION_NAME=${WEATHER_LOCATION_NAME:-Kaiu, Raplamaa}
    volumes:
      - api_data:/data
    networks:
      - web
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  api_data:
    driver: local

networks:
  web:
    driver: bridge